### ISSUE TITLE
Capture the console.log errors

### ISSUE THREAD

**Issue by amitaibu** [minkphp/MinkSelenium2Driver#189]
I'm using Behat + phantomJS, and would like to see the errors thrown to the `console.log`.

CasperJs allows binding to this event:

``` javascript
casper.on('remote.message', function(resource) {
  this.log('LOG:' + resource);
});
```

This is provided by [phantomjs](http://phantomjs.org/api/webpage/handler/on-console-message.html)

Would it be possible to have something similar in Behat? I can try to code it, but preferred to get some guidance on what's the proper why.

**Comment by gimler** [comment]
@amitaibu can you please post the final code

**Comment by amitaibu** [comment]
Sorry, I no longer have the code that used it, but it seems `evaluateScript` was what I've used.

**Comment by DWmodem** [comment]
@amitaibu 
My solution was to set up a listener in the apps javascript:

```
testing = {
    errors: []
};
window.onerror = function(error, url, line) {
    testing.errors.push(error + ". Line: " + line);
};
```
And then in behat, in afterSuite, afterStep or whenever you feel is convenient, 
```
$context->getSession()->evaluateScript("testing.errors");
```

**Comment by stof** [comment]
The issue about doing it in a generic way in Mink is that pages can be reloaded at any time (especially when using a JS-enabled browser as this could be triggered by JS rather than a Mink action) and any JS API highjacking would be lost at this point. It would be almost impossible to make it reliable.

The solution of @DWmodem is much easier, even though it forces your app to have some JS code doing the error collection part (which solve most issues about page reloads, as injecting the code is part of the page load, so the only remaining issue is the fact that issues from previous page loads are lost).

So I'm in favor of marking this as "Won't fix".

**Comment by aik099** [comment]
Agreed.

**Comment by stof** [comment]
OK, then closing this as you agreed with me
