### ISSUE TITLE
Converting getAttribute to use pure JS code fails for select input option.

### ISSUE THREAD

**Issue by rajeshtaneja** [minkphp/MinkSelenium2Driver#195]
With 8b209b19eea1a4f96e4543edc64544e8b4f510ea change moving to pure JS code for attribute retrieval is failing while retrieving selected attribute form select option

Attributed selected is not set on select boxes, and JS code is returning '' (empty).

**Comment by aik099** [comment]
Of course, because `getAttribute` now works as `attr` in latest jQuery version: only returns value of HTML attribute. Before it was working as `attr` in older jQuery versions: returning value of object property with same name, when attribute was missing.

If your code was replying on older behavior of `getAttribute` version, then it would also have failed when you've started to user another driver.

Here is what you can do currently:
1. either operate on SELECT element instead of option, because it has method (in PHP) for getting current value
2. or use `evaluateScript` method of `Session` to get `.selected` property of your option

**Comment by rajeshtaneja** [comment]
Thanks for the input Alexander,

Will check and fix this as per your suggestion.

**Comment by aik099** [comment]
If all will work out for you then you can close this ticket.

**Comment by rajeshtaneja** [comment]
Thanks Alexander,

Closing this ticket.
