### ISSUE TITLE
Not working after update to Chrome 54

### ISSUE THREAD

**Issue by adridev** [minkphp/MinkSelenium2Driver#249]
Hi, 

after the update that Google published yesterday for Chrome, Behat is not working anymore. 

Error: Could not open connection: Connection refused.

I'm not sure if It is related to this package. If it isn't this could be taken as advice. 

After rollback chrome to the version 53 everything is working again. 

I'll try to address the problem.

Regards!

**Comment by aik099** [comment]
Since Selenium API haven't changed I'm guessing it's problem of Selenium Server itself OR most likely it's Chrome driver.

Does it work with Firefox?

**Comment by stof** [comment]
this should indeed be reported to Selenium, as Mink does not connect to chrome directly.

Btw, make sure you use ChromeDriver 2.24, as older versions of ChromeDriver are known to be incompatible with Chrome 54 according to the changelog of their release: http://chromedriver.storage.googleapis.com/2.24/notes.txt

**Comment by adridev** [comment]
Ok, thank you guys. At least this issue could avoid some headaches to someone. 

I'll close it.

**Comment by stof** [comment]
this is a generic case for Selenium: always make sure you use an uptodate version of Selenium and of the browser driver, because browser updates tend to break compat (this is why Selenium transferred the responsibility of drivers to each browser maker btw, as drivers are better kept uptodate this way)
